### ISSUE TITLE
Scalling X-axis values in plots

### ISSUE THREAD

**Issue by MadhuMPandurangi** [MadhuMPandurangi/RP_DataCompression#18]
# Scalling X-axis values in plots
As shown in the below figure, X-axis values need to be visible properly.
Now it is overlapping. Alternate values can be printed or if the x-axis values are more, then relatively scaling down (dynamically) the number of x-axis values is expected.
![image](https://user-images.githubusercontent.com/27917751/230916549-e6e4be96-5e74-463f-a9e4-4a375224386a.png)

**Comment by PotuRevanth** [comment]
#Use this code instead
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('CPU usage in percentage')
plt.xlabel('Time')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()
